### ISSUE TITLE
IBM Cloud ROKS integrated use of Let's encrypt for routes creates issues with ESO Deployment

### ISSUE THREAD

**Issue by butler54** [validatedpatterns/common#388]
I've deployed a validated-patterns based cluster which was derived from `multicloud-gitops` based on this repo:

- https://github.com/butler54/validated-patterns-demos

When deploying I was using 'Red Hat Openshift on IBM Cloud' where:

1. It was a VPC cluster (e.g. not classic)
2. The public service endpoints were enabled (e.g. routes are on the internet by default).

Here I was using the default route hostname (described here): https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_routes using an "IBM provided domain".

By default the routes appear to be encrypted with lets encrypt certs including the console. So any re-encrypt/Redirect or edge/Redirect routes have usable public certs.

The adverse impact of this is that by default the External secrets Operator enforces a particular certificate chain.

The following commit enabled the ESO to function. however, does decrease security posture.
https://github.com/butler54/validated-patterns-demos/commit/e427f9911f467891eddabfb199924ee4d540852e

## references
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_routes

**Comment by mbaldessari** [comment]
Thanks for raising this @butler54 ! At first I was a bit puzzled, because we do have some experimental support for letsencrypt and it all works okay there (I just retested it). I looked into this a bit more and the reason letsencrypt works for us, is because we deploy it with cert-manager which takes care of injecting the letsencrypt CA in the kube-root-ca.crt by default:
```
oc extract -n golang-external-secrets configmap/kube-root-ca.crt --to=- > /tmp/letsencrypt1.txt  ;  openssl storeutl -noout -text /tmp/letsencrypt1.txt | grep "Issuer:"
# ca.crt
        Issuer: OU=openshift, CN=kube-apiserver-lb-signer
        Issuer: OU=openshift, CN=kube-apiserver-localhost-signer
        Issuer: OU=openshift, CN=kube-apiserver-service-network-signer
        Issuer: CN=openshift-kube-apiserver-operator_localhost-recovery-serving-signer@1699294589
        Issuer: C=US, O=Let's Encrypt, CN=R3
        Issuer: C=US, O=Internet Security Research Group, CN=ISRG Root X1
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
```

This does not happen on an IBM cloud:
```
oc extract -n golang-external-secrets configmap/kube-root-ca.crt --to=- > /tmp/letsencrypt2.txt  ;  openssl storeutl -noout -text /tmp/letsencrypt2.txt | grep "Issuer:"
# ca.crt
        Issuer: CN=root-ca-1699287502
        Issuer: CN=root-ca-1699287502
        Issuer: CN=root-ca-1699287502
        Issuer: CN=root-ca-1699287502
        Issuer: CN=cluster-signer-1699287502
        Issuer: CN=cluster-signer-1699287502
        Issuer: CN=cluster-signer-1699287502
        Issuer: CN=cluster-signer-1699287502
```

So either we find a simple way to inject the letsencrypt CA (or other CAs) into the kube-root-ca.crt configmap when on IBM cloud, or we need to come up with some not-too-horrible way to override which CA gets used in ESO.

**Comment by mbaldessari** [comment]
(I'll add that the cleanest solution is for IBM to add the CA cert they use automatically to the default CA bundle, but I suspect that might be a bit more complicated ;) )

**Comment by mbaldessari** [comment]
So via https://github.com/validatedpatterns/multicloud-gitops/pull/303 and https://github.com/validatedpatterns/common/pull/391 I think this one is addressed, so I am going ahead and closing it. Do scream, if you think it needs more work ;)
