### ISSUE TITLE
Framework support for private repo additions to ArgoCD instances

### ISSUE THREAD

**Issue by claudiol** [validatedpatterns/common#411]
In a disconnected environment customers will have git repos that house their source code.
To deploy our validated patterns the private repositories will have to be configured in ArgoCD with a provided customer certificate for the git repository.

This will have to be configured by the patterns operator at creation of the ArgoCD instance creation for the pattern.

If application manifests are located in private repository then repository credentials have to be configured.  

Proposal:
- Extend the framework to accept private git repository configuration 
- If private git repository configuration is provided the framework should add this to the ArgoCD instances

**Comment by claudiol** [comment]
@mbaldessari You are always one step ahead! I will look at the PR's.

**Comment by mbaldessari** [comment]
Given https://validatedpatterns.io/blog/2023-12-20-private-repos/ landed I am going to close this one
