### ISSUE TITLE
preview-all is not rendering the clusterGroup chart

### ISSUE THREAD

**Issue by mbaldessari** [validatedpatterns/common#452]
It is currently rendering only the listed applications. To have a quick validation of what is being worked on without deploying it, it'd be useful to also render the clusterGroup chart which is the entry point for a pattern.

We should also allow overriding some of the local lookups we do against the cluster here:
```
platform=$(oc get Infrastructure.config.openshift.io/cluster  -o jsonpath='{.spec.platformSpec.type}')
ocpversion=$(oc get clusterversion/version -o jsonpath='{.status.desired.version}' | awk -F. '{print $1"."$2}')
domain=$(oc get Ingress.config.openshift.io/cluster -o jsonpath='{.spec.domain}' | sed 's/^apps.//')
```

This will allow a simple way to see how things change when a user changes the platform etc.

**Comment by wadebee** [comment]
This looks great. Thanks @mbaldessari. 

Implementation of this will be helpful for overall debugging of generated VP output and could allow for additional automated testing scenarios.

**Comment by mbaldessari** [comment]
The override part should be taken care via https://github.com/validatedpatterns/common/pull/453 . Is that more or less what you were looking for?

**Comment by mbaldessari** [comment]
Ok I think most of the stuff should be fixed now. preview-all is still very imperfect and is unlikely to ever be an exact 1-1 replica of what happens in-cluster, but it should now be a fairly good approximation that is sufficiently useful to have a quick peek on things before deploying.
As usual let me know if I missed anything and thanks again for bringing these issues up ;)
