### ISSUE TITLE
Support for merging of namespaces, projects, subscriptions and application in overrides/values-common.yaml 

### ISSUE THREAD

**Issue by wadebee** [validatedpatterns/common#459]
Scenario:

Our company has a base set of namespaces/projects/subscriptions and application that we want deployed in all clusters (hub and spokes).

We attempted to implement this with a values-common.yaml in the overrides folder.

When we include this common file into values-hub.yaml or values-spoke as an entry in sharedValueFiles: it does not work. It appears that helm just overwrites the hub/spoke yaml namespaces/projects/subscriptions/applications with the contents of common.yaml.

**Comment by claudiol** [comment]
@wadebee we are working on a solution for this. This will require for us to update the framework to support maps for the **projects** and **namespaces** sections.  The idea is that if you define **projects** in two different values files using a map construct we will be able to merge both definition of **projects** into one.

Example:
**values-group-one.yaml**
'''
clusterGroup:
  ...
  sharedValueFiles:
  - 'overrides/values-common.yaml'
  ...
  projects:
    project1:
    project2:
  ...
'''
**values-common.yaml**
'''
clusterGroup:
  ...
  projects:
    project3:
    project4:
'''
The result will be 
'''
clusterGroup:
  ...
  sharedValueFiles:
  - 'overrides/values-common.yaml'
  ...
  projects:
    project1:
    project2:
    project3:
    project4:
'''
Notice that it would not be described as a list but the framework will support either a list of projects or the map of projects. We will keep you posted on our progress. We currently have an initial implementation that I will review with @mbaldessari tomorrow morning.

**Comment by claudiol** [comment]
@wadebee We have tested your scenario and it is working with the new changes.  We will create a PR against common today, review it and merge it.
